version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ktor-sample
      - POSTGRES_PASSWORD=ktor-sample
      - POSTGRES_DB=ktor-sample
